In [40]:
#1
import numpy as np

In [41]:
#2
w = np.array([1, 2, 3, 45, 67, 89, 22, 33, 44]) # обычный массив чего то (тут чисел)
z = np.zeros((3, 3)) # Массив матрица 3 на 3 заполненный нулями
o = np.ones((3, 3, 2)) # Трехмерный массив 3 на 3 на 2 заполненный единицами
p = np.arange(0, 10, 2)  # Массив последовательность чисел от 0 до 10 с шагом 2 
# Вывод всех массивов
s = (w, z, o, p)
names = ('w','z','o','p')
for i in s:
  print(f"{i} \n")

[ 1  2  3 45 67 89 22 33 44] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]] 

[0 2 4 6 8] 



In [42]:
#3
for i in range(len(s)):
  print(f" {names[i]}: shape - {s[i].shape} type - {s[i].dtype}")

 w: shape - (9,) type - int64
 z: shape - (3, 3) type - float64
 o: shape - (3, 3, 2) type - float64
 p: shape - (5,) type - int64


In [43]:
#4
print(w[3:6]) # Вывод 4-6 элементов масссива w
print(p[0]) # Вывод первого элемента массива p

[45 67 89]
0


In [44]:
#5
#Создание 2 двумерных массивов матриц размерностью 2 на 3 и их сложение
a1 = np.array([[1, 2 ,3], [4, 5, 6]])
a2 = np.array([[11, 22, 33], [44, 55, 66]])
a3=a1+a2
print(a3)
print()
#Вычисление среднего значиние по столбцам
print(np.mean(a3, axis = 0))
print()
#Добавим выброс в матрицу и вычислим медиану
a3[1][2]=1000
print(np.median(a3))

[[12 24 36]
 [48 60 72]]

[30. 42. 54.]

42.0
